//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 06:25:23 PM IST 
//


package com.pennant.webservice.schema;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ExtFinanceDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtFinanceDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FinType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FinReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FinCcy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RepayRateBasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ScheduleMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AllowGrcPeriod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GrcSchdMthd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AllowGrcCpz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProfitDaysBasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LovDescCustCIF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FinStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FinAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="DpToBank" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="DpToSupplier" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpGracePft" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpGraceCpz" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpGorssGracePft" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpRepayPft" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpTotalPft" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpFirstInst" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpLastInst" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpLastInstPft" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpRateAtStart" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ExpRateAtGrcEnd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtFinanceDetails", propOrder = {
    "finType",
    "finReference",
    "finCcy",
    "repayRateBasis",
    "scheduleMethod",
    "allowGrcPeriod",
    "grcSchdMthd",
    "allowGrcCpz",
    "profitDaysBasis",
    "lovDescCustCIF",
    "finStartDate",
    "finAmount",
    "dpToBank",
    "dpToSupplier",
    "expGracePft",
    "expGraceCpz",
    "expGorssGracePft",
    "expRepayPft",
    "expTotalPft",
    "expFirstInst",
    "expLastInst",
    "expLastInstPft",
    "expRateAtStart",
    "expRateAtGrcEnd"
})
public class ExtFinanceDetails {

    @XmlElement(name = "FinType", required = true)
    protected String finType;
    @XmlElement(name = "FinReference", required = true)
    protected String finReference;
    @XmlElement(name = "FinCcy", required = true)
    protected String finCcy;
    @XmlElement(name = "RepayRateBasis", required = true)
    protected String repayRateBasis;
    @XmlElement(name = "ScheduleMethod", required = true)
    protected String scheduleMethod;
    @XmlElement(name = "AllowGrcPeriod", required = true)
    protected String allowGrcPeriod;
    @XmlElement(name = "GrcSchdMthd", required = true)
    protected String grcSchdMthd;
    @XmlElement(name = "AllowGrcCpz", required = true)
    protected String allowGrcCpz;
    @XmlElement(name = "ProfitDaysBasis", required = true)
    protected String profitDaysBasis;
    @XmlElement(name = "LovDescCustCIF", required = true)
    protected String lovDescCustCIF;
    @XmlElement(name = "FinStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar finStartDate;
    @XmlElement(name = "FinAmount", required = true)
    protected BigDecimal finAmount;
    @XmlElement(name = "DpToBank", required = true)
    protected BigDecimal dpToBank;
    @XmlElement(name = "DpToSupplier", required = true)
    protected BigDecimal dpToSupplier;
    @XmlElement(name = "ExpGracePft", required = true)
    protected BigDecimal expGracePft;
    @XmlElement(name = "ExpGraceCpz", required = true)
    protected BigDecimal expGraceCpz;
    @XmlElement(name = "ExpGorssGracePft", required = true)
    protected BigDecimal expGorssGracePft;
    @XmlElement(name = "ExpRepayPft", required = true)
    protected BigDecimal expRepayPft;
    @XmlElement(name = "ExpTotalPft", required = true)
    protected BigDecimal expTotalPft;
    @XmlElement(name = "ExpFirstInst", required = true)
    protected BigDecimal expFirstInst;
    @XmlElement(name = "ExpLastInst", required = true)
    protected BigDecimal expLastInst;
    @XmlElement(name = "ExpLastInstPft", required = true)
    protected BigDecimal expLastInstPft;
    @XmlElement(name = "ExpRateAtStart", required = true)
    protected BigDecimal expRateAtStart;
    @XmlElement(name = "ExpRateAtGrcEnd", required = true)
    protected BigDecimal expRateAtGrcEnd;

    /**
     * Gets the value of the finType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinType() {
        return finType;
    }

    /**
     * Sets the value of the finType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinType(String value) {
        this.finType = value;
    }

    /**
     * Gets the value of the finReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinReference() {
        return finReference;
    }

    /**
     * Sets the value of the finReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinReference(String value) {
        this.finReference = value;
    }

    /**
     * Gets the value of the finCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinCcy() {
        return finCcy;
    }

    /**
     * Sets the value of the finCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinCcy(String value) {
        this.finCcy = value;
    }

    /**
     * Gets the value of the repayRateBasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepayRateBasis() {
        return repayRateBasis;
    }

    /**
     * Sets the value of the repayRateBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepayRateBasis(String value) {
        this.repayRateBasis = value;
    }

    /**
     * Gets the value of the scheduleMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleMethod() {
        return scheduleMethod;
    }

    /**
     * Sets the value of the scheduleMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleMethod(String value) {
        this.scheduleMethod = value;
    }

    /**
     * Gets the value of the allowGrcPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowGrcPeriod() {
        return allowGrcPeriod;
    }

    /**
     * Sets the value of the allowGrcPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowGrcPeriod(String value) {
        this.allowGrcPeriod = value;
    }

    /**
     * Gets the value of the grcSchdMthd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrcSchdMthd() {
        return grcSchdMthd;
    }

    /**
     * Sets the value of the grcSchdMthd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrcSchdMthd(String value) {
        this.grcSchdMthd = value;
    }

    /**
     * Gets the value of the allowGrcCpz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowGrcCpz() {
        return allowGrcCpz;
    }

    /**
     * Sets the value of the allowGrcCpz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowGrcCpz(String value) {
        this.allowGrcCpz = value;
    }

    /**
     * Gets the value of the profitDaysBasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitDaysBasis() {
        return profitDaysBasis;
    }

    /**
     * Sets the value of the profitDaysBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitDaysBasis(String value) {
        this.profitDaysBasis = value;
    }

    /**
     * Gets the value of the lovDescCustCIF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLovDescCustCIF() {
        return lovDescCustCIF;
    }

    /**
     * Sets the value of the lovDescCustCIF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLovDescCustCIF(String value) {
        this.lovDescCustCIF = value;
    }

    /**
     * Gets the value of the finStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinStartDate() {
        return finStartDate;
    }

    /**
     * Sets the value of the finStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinStartDate(XMLGregorianCalendar value) {
        this.finStartDate = value;
    }

    /**
     * Gets the value of the finAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinAmount() {
        return finAmount;
    }

    /**
     * Sets the value of the finAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinAmount(BigDecimal value) {
        this.finAmount = value;
    }

    /**
     * Gets the value of the dpToBank property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDpToBank() {
        return dpToBank;
    }

    /**
     * Sets the value of the dpToBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDpToBank(BigDecimal value) {
        this.dpToBank = value;
    }

    /**
     * Gets the value of the dpToSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDpToSupplier() {
        return dpToSupplier;
    }

    /**
     * Sets the value of the dpToSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDpToSupplier(BigDecimal value) {
        this.dpToSupplier = value;
    }

    /**
     * Gets the value of the expGracePft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpGracePft() {
        return expGracePft;
    }

    /**
     * Sets the value of the expGracePft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpGracePft(BigDecimal value) {
        this.expGracePft = value;
    }

    /**
     * Gets the value of the expGraceCpz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpGraceCpz() {
        return expGraceCpz;
    }

    /**
     * Sets the value of the expGraceCpz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpGraceCpz(BigDecimal value) {
        this.expGraceCpz = value;
    }

    /**
     * Gets the value of the expGorssGracePft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpGorssGracePft() {
        return expGorssGracePft;
    }

    /**
     * Sets the value of the expGorssGracePft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpGorssGracePft(BigDecimal value) {
        this.expGorssGracePft = value;
    }

    /**
     * Gets the value of the expRepayPft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpRepayPft() {
        return expRepayPft;
    }

    /**
     * Sets the value of the expRepayPft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpRepayPft(BigDecimal value) {
        this.expRepayPft = value;
    }

    /**
     * Gets the value of the expTotalPft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpTotalPft() {
        return expTotalPft;
    }

    /**
     * Sets the value of the expTotalPft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpTotalPft(BigDecimal value) {
        this.expTotalPft = value;
    }

    /**
     * Gets the value of the expFirstInst property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpFirstInst() {
        return expFirstInst;
    }

    /**
     * Sets the value of the expFirstInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpFirstInst(BigDecimal value) {
        this.expFirstInst = value;
    }

    /**
     * Gets the value of the expLastInst property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpLastInst() {
        return expLastInst;
    }

    /**
     * Sets the value of the expLastInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpLastInst(BigDecimal value) {
        this.expLastInst = value;
    }

    /**
     * Gets the value of the expLastInstPft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpLastInstPft() {
        return expLastInstPft;
    }

    /**
     * Sets the value of the expLastInstPft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpLastInstPft(BigDecimal value) {
        this.expLastInstPft = value;
    }

    /**
     * Gets the value of the expRateAtStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpRateAtStart() {
        return expRateAtStart;
    }

    /**
     * Sets the value of the expRateAtStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpRateAtStart(BigDecimal value) {
        this.expRateAtStart = value;
    }

    /**
     * Gets the value of the expRateAtGrcEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExpRateAtGrcEnd() {
        return expRateAtGrcEnd;
    }

    /**
     * Sets the value of the expRateAtGrcEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExpRateAtGrcEnd(BigDecimal value) {
        this.expRateAtGrcEnd = value;
    }

}
