package com.pennanttech.bajaj.process.datamart;

public enum DataMartTable {
	DM_APPLICANT_DETAILS, DM_ADDRESS_DETAILS, DM_APPLICATION_DETAILS, DM_BOUNCE_DETAILS, DM_COAPPLICANT_DETAILS, DM_DISB_DETAILS_DAILY, FORECLOSURECHARGES, DM_HTS_UNADJUSTED_AMT, DM_INSURANCE_DETAILS, DM_IVR_GATEWAY_FLEXI, DM_LEA_DOC_DTL, DM_LOAN_DETAILS_DAILY, DM_LOAN_VOUCHER_DETAILS, DM_LOANWISE_CHARGE_DETAILS, DM_LOANWISE_REPAYSCHD_DTLS, DM_NOC_ELIGIBLE_LOANS, DM_OPENECS_DETAILS, DM_PREPAYMENT_DETAILS, DM_PRESENTATION_DETAILS, DM_PROPERTY_DTL, DM_RESCH_DETAILS_DAILY, DM_SEND_SOA_EMAIL, DM_SUBQ_DISB_DETAILS, DM_WRITEOFF_DETAILS;
}
