//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 06:25:23 PM IST 
//


package com.pennant.webservice.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExtFinanceDetails" type="{http://www.pennant.com/PFSService/schema}ExtFinanceDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extFinanceDetails"
})
@XmlRootElement(name = "PFSLoanCreationRequest")
public class PFSLoanCreationRequest {

    @XmlElement(name = "ExtFinanceDetails", required = true)
    protected ExtFinanceDetails extFinanceDetails;

    /**
     * Gets the value of the extFinanceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ExtFinanceDetails }
     *     
     */
    public ExtFinanceDetails getExtFinanceDetails() {
        return extFinanceDetails;
    }

    /**
     * Sets the value of the extFinanceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtFinanceDetails }
     *     
     */
    public void setExtFinanceDetails(ExtFinanceDetails value) {
        this.extFinanceDetails = value;
    }

}
