DROP TABLE DR_EMIHOLIDAY;
CREATE TABLE DR_EMIHOLIDAY
   (	
    FINREFERENCE VARCHAR(20),
    EHSTARTDATE TIMESTAMP,
    EHENDDATE TIMESTAMP,
    EHINST NUMERIC(2,0),
    EHMETHOD VARCHAR(2),
    BOUNCEWAIVER boolean,
    APPDATE TIMESTAMP,
    EHSTATUS VARCHAR(1),
    EHSTATUSREMARKS VARCHAR(50),
    BRANCHCODE VARCHAR(8),
    PRODUCTTYPE VARCHAR(8),
    FINTYPE VARCHAR(8),
    OLDBUCKET NUMERIC(3,0),
    NEWBUCKET NUMERIC(3,0),
    DPD NUMERIC(4,0),
    OLDEMIOS NUMERIC(18,0),
    NEWEMIOS NUMERIC(18,0),
    OLDBALTENURE NUMERIC(3,0),
    NEWBALTENURE NUMERIC(3,0),
    OLDMATURITY TIMESTAMP,
    NEWMATURITY TIMESTAMP,
    LASTBILLEDDATE TIMESTAMP,
    LASTBILLEDINSTNO NUMERIC(3,0),
    ACTLOANAMOUNT NUMERIC(18,0),
    OLDTENURE NUMERIC(3,0),
    NEWTENURE NUMERIC(3,0),
    OLDINTEREST NUMERIC(18,0),
    NEWINTEREST NUMERIC(18,0),
    CPZINTEREST NUMERIC(18,0),
    OLDMAXUNPLANNEDEMI NUMERIC(3,0),
    NEWMAXUNPLANNEDEMI NUMERIC(3,0),
    OLDAVAILEDUNPLANEMI NUMERIC(3,0),
    NEWAVAILEDUNPLANEMI NUMERIC(3,0),
    OLDFINALEMI NUMERIC(18,0),
    NEWFINALEMI NUMERIC(18,0),
    LASTMNTDATE TIMESTAMP
   );
   
   CREATE INDEX IDX_DR_EMIHOLIDAY_FINREFERENCE ON DR_EMIHOLIDAY (FINREFERENCE);
  
   
INSERT INTO DR_EMIHOLIDAY (FINREFERENCE, EHSTARTDATE, EHENDDATE, EHINST, EHMETHOD) 
VALUES ('H4F4RLP0125149', '2020-02-01', '2020-05-31', 2, 'CT');
