--DROP TABLE DR_EMIHOLIDAY;
CREATE TABLE DR_EMIHOLIDAY
   (	
    FINREFERENCE VARCHAR(20),
    EHSTARTDATE DATE,
    EHENDDATE DATE,
    EHINST DECIMAL(2,0),
    EHMETHOD VARCHAR(2),
    BOUNCEWAIVER bit,
    APPDATE DATE,
    EHSTATUS VARCHAR(1),
    EHSTATUSREMARKS VARCHAR(50),
    BRANCHCODE VARCHAR(8),
    PRODUCTTYPE VARCHAR(8),
    FINTYPE VARCHAR(8),
    OLDBUCKET DECIMAL(3,0),
    NEWBUCKET DECIMAL(3,0),
    DPD DECIMAL(4,0),
    OLDEMIOS DECIMAL(18,0),
    NEWEMIOS DECIMAL(18,0),
    OLDBALTENURE DECIMAL(3,0),
    NEWBALTENURE DECIMAL(3,0),
    OLDMATURITY DATETIME,
    NEWMATURITY DATETIME,
    LASTBILLEDDATE DATETIME,
    LASTBILLEDINSTNO DECIMAL(3,0),
    ACTLOANAMOUNT DECIMAL(18,0),
    OLDTENURE DECIMAL(3,0),
    NEWTENURE DECIMAL(3,0),
    OLDINTEREST DECIMAL(18,0),
    NEWINTEREST DECIMAL(18,0),
    CPZINTEREST DECIMAL(18,0),
    OLDMAXUNPLANNEDEMI DECIMAL(3,0),
    NEWMAXUNPLANNEDEMI DECIMAL(3,0),
    OLDAVAILEDUNPLANEMI DECIMAL(3,0),
    NEWAVAILEDUNPLANEMI DECIMAL(3,0),
    OLDFINALEMI DECIMAL(18,0),
    NEWFINALEMI DECIMAL(18,0),
    LASTMNTDATE DATETIME
   );
   
CREATE INDEX IDX_DR_EMIHOLIDAY ON DR_EMIHOLIDAY (FINREFERENCE);
  
   
INSERT INTO DR_EMIHOLIDAY (FINREFERENCE, EHSTARTDATE, EHENDDATE, EHINST, EHMETHOD) VALUES ('H4F4RLP0125149', '01-02-20', '31-05-20', 2, 'CT');